use_frameworks!

platform :ios, '8.0'

target 'XALFrameworksRelease_Example' do
  pod 'XALFrameworksRelease', :path => '../'

  target 'XALFrameworksRelease_Tests' do
    inherit! :search_paths

    
  end
end
