//
//  AlexEventsConstant.h
//  Pods
//
//  Created by apus on 2019/6/25.
//

#ifndef AlexEventsConstant_h
#define AlexEventsConstant_h

#import <Foundation/Foundation.h>

/** Alex公共事件-点击 */
FOUNDATION_EXPORT const NSUInteger XALEX_CLICK;
/** 点击的名称 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_NAME_STRING;
/** 点击的分类 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_CATEGORY_STRING;
/** 点击的类型 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_TYPE_STRING;
/** 点击的样式 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_STYLE_STRING;
/** 点击的动画 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_ANIMATION_STRING;
/** 点击项的包名 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_PACKAGE_STRING;
/** 点击的布局位置，用于定位一维空间的布局位置 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_POSITION_STRING;
/** 点击的横向布局位置，用于定位二维空间的布局位置 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_POSITION_X_INT;
/** 点击的纵向布局位置，用于定位二维空间的布局位置 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_POSITION_Y_INT;
/** 点击的文本内容 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_TEXT_STRING;
/** 点击后触发的url链接 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_URL_STRING;
/** 点击的组件所在的容器组件的名称 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_CONTAINER_STRING;
/** 点击时的源位置 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_FROM_SOURCE_STRING;
/** 点击后的目标位置 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_TO_DESTINATION_STRING;
/** 点击的结果 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_RESULT_CODE_STRING;
/** 点击的组件的标记 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_FLAG_STRING;
/** 编号 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_ID_STRING;
/** 语言 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_INPUT_LANGUAGE_STRING;
/** 选中的位置 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_SELECTION_POSITION_INT;
/** 源页面 */
FOUNDATION_EXPORT NSString *const XALEX_CLICK_FROM_PAGE_STRING;

/** Alex公共事件-搜索 */
FOUNDATION_EXPORT NSUInteger const XALEX_SEARCH;
/** 搜索的内容 */
FOUNDATION_EXPORT NSString *const XALEX_SEARCH_QUERY_STRING;
/** 搜索的触发方式 */
FOUNDATION_EXPORT NSString *const XALEX_SEARCH_TRIGGER_STRING;
/** 搜索的源位置 */
FOUNDATION_EXPORT NSString *const XALEX_SEARCH_FROM_SOURCE_STRING;
/** 搜索引擎名称 */
FOUNDATION_EXPORT NSString *const XALEX_SEARCH_SEARCH_ENGINE_STRING;
/** 搜索垂直频道 */
FOUNDATION_EXPORT NSString *const XALEX_SEARCH_TAB_STRING;
/** 搜索页之前的页面 */
FOUNDATION_EXPORT NSString *const XALEX_SEARCH_FROM_PAGE_STRING;
/** 垂直频道所处位置 */
FOUNDATION_EXPORT NSString *const XALEX_SEARCH_POSITION_STRING;
/** 内置的搜索引擎 */
FOUNDATION_EXPORT NSString *const XALEX_SEARCH_INNER_SEARCH_ENGINE_STRING;
/** 搜索的类型 */
FOUNDATION_EXPORT NSString *const XALEX_SEARCH_TYPE_STRING;

/** Alex公共事件-设置状态 */
FOUNDATION_EXPORT const NSUInteger XALEX_SET_STATE;
/** 设置状态的名称 */
FOUNDATION_EXPORT NSString *const XALEX_SET_STATE_NAME_STRING;
/** 设置前的状态 */
FOUNDATION_EXPORT NSString *const XALEX_SET_STATE_FROM_STATE_STRING;
/** 设置后的状态 */
FOUNDATION_EXPORT NSString *const XALEX_SET_STATE_TO_STATE_STRING;

/** 勾选事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_CHECK;
/** 勾选的名称 */
FOUNDATION_EXPORT NSString *const XALEX_CHECK_NAME_STRING;
/** 勾选项所在的页面 */
FOUNDATION_EXPORT NSString *const XALEX_CHECK_FROM_SOURCE_STRING;
/** 是否已勾选 */
FOUNDATION_EXPORT NSString *const XALEX_CHECK_CHECKED_BOOL;

/** 列表编辑事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_LIST_EDIT;
/** 列表的类型 */
FOUNDATION_EXPORT NSString *const XALEX_LIST_EDIT_LIST_TYPE_STRING;
/** 列表的动作 */
FOUNDATION_EXPORT NSString *const XALEX_LIST_EDIT_ACTION_STRING;
/** 列表的元素 */
FOUNDATION_EXPORT NSString *const XALEX_LIST_EDIT_ELEMENT_STRING;
/** 展示该列表的源页面 */
FOUNDATION_EXPORT NSString *const XALEX_LIST_EDIT_FROM_SOURCE_STRING;
/** 列表编辑的方式 */
FOUNDATION_EXPORT NSString *const XALEX_LIST_EDIT_MODE_STRING;

/** 分享事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_SHARE;
/** 分享的源位置 */
FOUNDATION_EXPORT NSString *const XALEX_SHARE_FROM_SOURCE_STRING;
/** 分享的目标位置 */
FOUNDATION_EXPORT NSString *const XALEX_SHARE_TO_DESTINATION_STRING;
/** 分享的资源的访问地址 */
FOUNDATION_EXPORT NSString *const XALEX_SHARE_URL_STRING;
/** 分享的文件类型 */
FOUNDATION_EXPORT NSString *const XALEX_SHARE_FILE_TYPE_STRING;
/** 分享时输入的文本描述 */
FOUNDATION_EXPORT NSString *const XALEX_SHARE_TEXT_STRING;
/** 来源ID */
FOUNDATION_EXPORT NSString *const XALEX_SHARE_SOURCE_ID_STRING;
/** 分享的类型 */
FOUNDATION_EXPORT NSString *const XALEX_SHARE_TYPE_STRING;

/** 移动事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_MOVE;
/** 要移动的组件的名称 */
FOUNDATION_EXPORT NSString *const XALEX_MOVE_NAME_STRING;
/** 移动的分类 */
FOUNDATION_EXPORT NSString *const XALEX_MOVE_CATEGORY_STRING;
/** 移动的类型 */
FOUNDATION_EXPORT NSString *const XALEX_MOVE_TYPE_STRING;
/** 移动的组件所在的容器组件的名称 */
FOUNDATION_EXPORT NSString *const XALEX_MOVE_CONTAINER_STRING;
/** 移动项的包名 */
FOUNDATION_EXPORT NSString *const XALEX_MOVE_PACKAGE_STRING;
/** 移动的源位置，一维空间的布局位置 */
FOUNDATION_EXPORT NSString *const XALEX_MOVE_FROM_POSITION_STRING;
/** 移动的目标位置，一维空间的布局位置 */
FOUNDATION_EXPORT NSString *const XALEX_MOVE_TO_POSITION_STRING;
/** 移动的源位置，二维空间的布局位置 */
FOUNDATION_EXPORT NSString *const XALEX_MOVE_FROM_POSITION_X_INT;
/** 移动的源位置，二维空间的布局位置 */
FOUNDATION_EXPORT NSString *const XALEX_MOVE_FROM_POSITION_Y_INT;
/** 移动的源页面 */
FOUNDATION_EXPORT NSString *const XALEX_MOVE_FROM_SOURCE_STRING;
/** 移动的目标页面 */
FOUNDATION_EXPORT NSString *const XALEX_MOVE_TO_DESTINATION_STRING;
/** 移动的目标位置，二维空间的布局位置 */
FOUNDATION_EXPORT NSString *const XALEX_MOVE_TO_POSITION_X_INT;
/** 移动的目标位置，二维空间的布局位置 */
FOUNDATION_EXPORT NSString *const XALEX_MOVE_TO_POSITION_Y_INT;
/** 移动的结果 */
FOUNDATION_EXPORT NSString *const XALEX_MOVE_RESULT_CODE_STRING;

/** 展示事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_SHOW;
/** 展示的名称 */
FOUNDATION_EXPORT NSString *const XALEX_SHOW_NAME_STRING;
/** 展示的样式 */
FOUNDATION_EXPORT NSString *const XALEX_SHOW_STYLE_STRING;
/** 展示的动画 */
FOUNDATION_EXPORT NSString *const XALEX_SHOW_ANIMATION_STRING;
/** 展示的组件所在的容器组件的名称 */
FOUNDATION_EXPORT NSString *const XALEX_SHOW_CONTAINER_STRING;
/** 展示的源位置 */
FOUNDATION_EXPORT NSString *const XALEX_SHOW_FROM_SOURCE_STRING;
/** 展示的时长 */
FOUNDATION_EXPORT NSString *const XALEX_SHOW_DURATION_INT;
/** 展示的间隔时间 */
FOUNDATION_EXPORT NSString *const XALEX_SHOW_INTERVAL_INT;
/** 展示的组件的标记 */
FOUNDATION_EXPORT NSString *const XALEX_SHOW_FLAG_STRING;
/** 展示的描述 */
FOUNDATION_EXPORT NSString *const XALEX_SHOW_TEXT_STRING;
/** 展示的类型 */
FOUNDATION_EXPORT NSString *const XALEX_SHOW_TYPE_STRING;

/** 下载事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_DOWNLOAD;
/** 下载编号 */
FOUNDATION_EXPORT NSString *const XALEX_DOWNLOAD_ID_STRING;
/** 下载中的动作，包括“start/pause/resume/end”。 */
FOUNDATION_EXPORT NSString *const XALEX_DOWNLOAD_ACTION_STRING;
/** 下载链接地址 */
FOUNDATION_EXPORT NSString *const XALEX_DOWNLOAD_LINK_ADDRESS_STRING;
/** 下载的文件类型 */
FOUNDATION_EXPORT NSString *const XALEX_DOWNLOAD_FILE_TYPE_STRING;
/** 下载的文件大小 */
FOUNDATION_EXPORT NSString *const XALEX_DOWNLOAD_FILE_SIZE_INT;
/** 下载所在的原页面的地址 */
FOUNDATION_EXPORT NSString *const XALEX_DOWNLOAD_REF_URL_STRING;
/** 下载到本地的位置 */
FOUNDATION_EXPORT NSString *const XALEX_DOWNLOAD_DOWNLOAD_LOCATION_STRING;
/** 下载时长，当action为end时传递。 */
FOUNDATION_EXPORT NSString *const XALEX_DOWNLOAD_TAKE_INT;
/** 下载请求的返回结果 */
FOUNDATION_EXPORT NSString *const XALEX_DOWNLOAD_RESULT_CODE_STRING;
/** 下载请求的返回信息 */
FOUNDATION_EXPORT NSString *const XALEX_DOWNLOAD_RESULT_INFO_STRING;
/** 下载的描述 */
FOUNDATION_EXPORT NSString *const XALEX_DOWNLOAD_TEXT_STRING;
/** 下载的来源 */
FOUNDATION_EXPORT NSString *const XALEX_DOWNLOAD_FROM_SOURCE_STRING;
/** 下载的名称 */
FOUNDATION_EXPORT NSString *const XALEX_DOWNLOAD_NAME_STRING;
/** 下载速度 */
FOUNDATION_EXPORT NSString *const XALEX_DOWNLOAD_DOWNLOAD_SPEED_DOUBLE;
/** 重试次数 */
FOUNDATION_EXPORT NSString *const XALEX_DOWNLOAD_RETRY_NUM_INT;

/** 隐藏事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_HIDE;
/** 隐藏的名称 */
FOUNDATION_EXPORT NSString *const XALEX_HIDE_NAME_STRING;
/** 隐藏的触发方式 */
FOUNDATION_EXPORT NSString *const XALEX_HIDE_TRIGGER_STRING;
/** 隐藏的原因 */
FOUNDATION_EXPORT NSString *const XALEX_HIDE_REASON_STRING;
/** 隐藏的组件的标记 */
FOUNDATION_EXPORT NSString *const XALEX_HIDE_FLAG_STRING;
/** 页面隐藏前的数量（比如选中的图片数） */
FOUNDATION_EXPORT NSString *const XALEX_HIDE_PATH_COUNT_INT;

/** 推荐事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_SUGGESTION;
/** 推荐的内容 */
FOUNDATION_EXPORT NSString *const XALEX_SUGGESTION_INPUT_STRING;
/** 推荐的热词 */
FOUNDATION_EXPORT NSString *const XALEX_SUGGESTION_HOTWORD_STRING;

/** 调试事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_DEBUG;
/** 调试的名称 */
FOUNDATION_EXPORT NSString *const XALEX_DEBUG_NAME_STRING;
/** 调试的动作 */
FOUNDATION_EXPORT NSString *const XALEX_DEBUG_ACTION_STRING;
/** 调试的类型 */
FOUNDATION_EXPORT NSString *const XALEX_DEBUG_TYPE_STRING;
/** 调试的文本描述 */
FOUNDATION_EXPORT NSString *const XALEX_DEBUG_TEXT_STRING;
/** 调试打点的源位置 */
FOUNDATION_EXPORT NSString *const XALEX_DEBUG_FROM_SOURCE_STRING;
/** 调试打点的目标位置 */
FOUNDATION_EXPORT NSString *const XALEX_DEBUG_TO_DESTINATION_STRING;
/** 请求响应的代码 */
FOUNDATION_EXPORT NSString *const XALEX_DEBUG_RESULT_CODE_STRING;
/** 调试的组件的标记 */
FOUNDATION_EXPORT NSString *const XALEX_DEBUG_FLAG_STRING;

/**  */
FOUNDATION_EXPORT const NSUInteger XALEX_PROFILER_IMAGE_PREDICTION;
/**  */
FOUNDATION_EXPORT const NSUInteger XALEX_PROFILER_IMAGE_PROFILE;

/** URL请求事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_URL_REQUEST;
/** URL请求的名称 */
FOUNDATION_EXPORT NSString *const XALEX_URL_REQUEST_URL_STRING;
/** 该URL请求的发起URL */
FOUNDATION_EXPORT NSString *const XALEX_URL_REQUEST_REFER_URL_STRING;
/** URL请求的返回结果 */
FOUNDATION_EXPORT NSString *const XALEX_URL_REQUEST_RESULT_CODE_STRING;

/** 操作事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_OPERATION;
/** 操作的名称 */
FOUNDATION_EXPORT NSString *const XALEX_OPERATION_NAME_STRING;
/** 操作的类别 */
FOUNDATION_EXPORT NSString *const XALEX_OPERATION_CATEGORY_STRING;
/** 操作的类型 */
FOUNDATION_EXPORT NSString *const XALEX_OPERATION_TYPE_STRING;
/** 操作的组件所在的容器组件的名称 */
FOUNDATION_EXPORT NSString *const XALEX_OPERATION_CONTAINER_STRING;
/** 操作的动作 */
FOUNDATION_EXPORT NSString *const XALEX_OPERATION_ACTION_STRING;
/** 操作项的包名 */
FOUNDATION_EXPORT NSString *const XALEX_OPERATION_PACKAGE_STRING;
/** 操作的源页面 */
FOUNDATION_EXPORT NSString *const XALEX_OPERATION_FROM_SOURCE_STRING;
/** 操作的目标页面 */
FOUNDATION_EXPORT NSString *const XALEX_OPERATION_TO_DESTINATION_STRING;
/** 操作的源位置，一维空间的布局位置 */
FOUNDATION_EXPORT NSString *const XALEX_OPERATION_FROM_POSITION_STRING;
/** 操作的目标位置，一维空间的布局位置 */
FOUNDATION_EXPORT NSString *const XALEX_OPERATION_TO_POSITION_STRING;
/** 操作的源位置，用于定位二维空间的布局位置 */
FOUNDATION_EXPORT NSString *const XALEX_OPERATION_FROM_POSITION_X_INT;
/** 操作的目标位置，用于定位二维空间的布局位置 */
FOUNDATION_EXPORT NSString *const XALEX_OPERATION_FROM_POSITION_Y_INT;
/** 操作的目标位置，用于定位二维空间的布局位置 */
FOUNDATION_EXPORT NSString *const XALEX_OPERATION_TO_POSITION_X_INT;
/** 操作的目标位置，用于定位二维空间的布局位置 */
FOUNDATION_EXPORT NSString *const XALEX_OPERATION_TO_POSITION_Y_INT;
/** 操作的触发方式 */
FOUNDATION_EXPORT NSString *const XALEX_OPERATION_TRIGGER_STRING;
/** 操作请求的URL */
FOUNDATION_EXPORT NSString *const XALEX_OPERATION_URL_STRING;
/** 操作请求的返回结果 */
FOUNDATION_EXPORT NSString *const XALEX_OPERATION_RESULT_CODE_STRING;

/** 选择事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_SELECT;
/** 选择的名称 */
FOUNDATION_EXPORT NSString *const XALEX_SELECT_NAME_STRING;
/** 选择的索引号 */
FOUNDATION_EXPORT NSString *const XALEX_SELECT_INDEX_INT;
/** 选择的源页面 */
FOUNDATION_EXPORT NSString *const XALEX_SELECT_FROM_SOURCE_STRING;
/** 选择的触发方式 */
FOUNDATION_EXPORT NSString *const XALEX_SELECT_TRIGGER_STRING;

/** 计数事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_COUNT;
/** 计数的事件实例名称 */
FOUNDATION_EXPORT NSString *const XALEX_COUNT_EVENT_NAME_STRING;
/** 计数的事件实例次数 */
FOUNDATION_EXPORT NSString *const XALEX_COUNT_EVENT_COUNT_INT;

/** 特权事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_VIP;
/** 特权事件的名称 */
FOUNDATION_EXPORT NSString *const XALEX_VIP_NAME_STRING;
/** 特权事件的传值 */
FOUNDATION_EXPORT NSString *const XALEX_VIP_VALUE_STRING;

/** 上传事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_UPLOAD;
/** 上传事件的名称 */
FOUNDATION_EXPORT NSString *const XALEX_UPLOAD_NAME_STRING;
/** 上传事件的传值 */
FOUNDATION_EXPORT NSString *const XALEX_UPLOAD_VALUE_STRING;

/** 内容展示事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_CONTENT_SHOW;
/** 服务器下发数据Session唯一识别 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHOW_SESSION_ID_STRING;
/** 内容唯一识别 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHOW_CONTENT_ID_STRING;
/** 名称 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHOW_NAME_STRING;
/** 内容类型，如视频/新闻/GIF/图集... */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHOW_CONTENT_TYPE_STRING;
/** 内容源 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHOW_CONTENT_SOURCE_STRING;
/** 预览内容所在列表中的位置 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHOW_POSITION_STRING;
/** 下发策略 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHOW_STRATEGY_STRING;
/** 内容所对应的UI模块/页面 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHOW_FROM_SOURCE_STRING;
/** 服务端下发的频道 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHOW_CONTENT_CHANNEL_ID_STRING;
/** 页面浏览进度（单位%） */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHOW_PERCENTAGE_DOUBLE;
/** 一级分类 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHOW_CATEGORY_ID_STRING;
/** 二级分类 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHOW_SUB_CLASS_ID_STRING;
/** 内容所在页面，客户端的位置 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHOW_CONTAINER_STRING;
/** 页面访问时长 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHOW_DURATION_INT;
/** 预留备用字段 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHOW_FLAG_STRING;
/** 内容合作方 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHOW_CONTENT_PARTNER_STRING;

/** 内容点击事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_CONTENT_CLICK;
/** 服务器下发数据Session唯一识别 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_CLICK_SESSION_ID_STRING;
/** 内容唯一识别 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_CLICK_CONTENT_ID_STRING;
/** 名称 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_CLICK_NAME_STRING;
/** 内容类型，视频/新闻/GIF/图集... */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_CLICK_CONTENT_TYPE_STRING;
/** 内容源 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_CLICK_CONTENT_SOURCE_STRING;
/** 预览内容曝光所对应的UI模块/页面 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_CLICK_FROM_SOURCE_STRING;
/** 预览内容所在列表中的位置 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_CLICK_POSITION_STRING;
/** 下发策略 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_CLICK_STRATEGY_STRING;
/** 服务端下发的频道 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_CLICK_CONTENT_CHANNEL_ID_STRING;
/** 一级分类 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_CLICK_CATEGORY_ID_STRING;
/** 二级分类 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_CLICK_SUB_CLASS_ID_STRING;
/** 预览内容曝光对应页面所在的UI页面/功能模块 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_CLICK_CONTAINER_STRING;
/** 预留备用字段 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_CLICK_FLAG_STRING;
/** 内容合作方 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_CLICK_CONTENT_PARTNER_STRING;

/** 详情展示事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_CONTENT_DISPLAY;
/** 服务器下发数据Session唯一识别 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DISPLAY_SESSION_ID_STRING;
/** 内容唯一识别 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DISPLAY_CONTENT_ID_STRING;
/** 内容类型 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DISPLAY_CONTENT_TYPE_STRING;
/** 内容源 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DISPLAY_CONTENT_SOURCE_STRING;
/** 浏览/观看时长（单位s） */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DISPLAY_DISPLAY_DURATION_INT;
/** 浏览/观看进度百分比 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DISPLAY_PERCENTAGE_DOUBLE;
/** 浏览/播放次数 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DISPLAY_TIMES_INT;
/** 当前详情页展示触发来源，通常为上一级页面 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DISPLAY_FROM_SOURCE_STRING;
/**  */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DISPLAY_FLAG_STRING;
/** 名称 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DISPLAY_NAME_STRING;
/** 视频时长（单位s） */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DISPLAY_VIDEO_DURATION_INT;
/** 加载时长（单位s） */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DISPLAY_LOADING_DURATION_INT;
/** 加载次数 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DISPLAY_LOADING_TIMES_INT;
/** 暂停次数 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DISPLAY_PAUSE_TIMES_INT;
/** 播放失败次数 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DISPLAY_PLAY_FAILURE_TIMES_INT;
/** 错误状态 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DISPLAY_RESULT_CODE_STRING;
/** 播放类型，例如主动播放、自动播放 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DISPLAY_PLAY_TYPE_STRING;
/** 页面访问时长（单位ms） */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DISPLAY_DURATION_INT;

/** 详情展示事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_CONTENT_SHARE;
/** 服务器下发数据Session唯一识别 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHARE_SESSION_ID_STRING;
/** 内容唯一识别 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHARE_CONTENT_ID_STRING;
/** 内容类型 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHARE_CONTENT_TYPE_STRING;
/** 被分享的内容所在UI模块或页面 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHARE_FROM_SOURCE_STRING;
/** 分享至应用包名 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHARE_TO_DESTINATION_STRING;
/**  */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHARE_FLAG_STRING;
/** 内容源 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHARE_CONTENT_SOURCE_STRING;
/** 名称 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_SHARE_NAME_STRING;

/** 内容下载事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_CONTENT_DOWNLOAD;
/** 服务器下发数据Session唯一识别 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DOWNLOAD_SESSION_ID_STRING;
/** 内容唯一识别 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DOWNLOAD_CONTENT_ID_STRING;
/** 名称 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_DOWNLOAD_NAME_STRING;

/** 点赞收藏事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_CONTENT_FAVORITE;
/** 服务器下发数据Session唯一识别 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_FAVORITE_SESSION_ID_STRING;
/** 内容唯一识别 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_FAVORITE_CONTENT_ID_STRING;
/** 内容类型 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_FAVORITE_CONTENT_TYPE_STRING;
/** 内容源 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_FAVORITE_CONTENT_SOURCE_STRING;
/** 操作行为 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_FAVORITE_ACTION_STRING;
/**  */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_FAVORITE_FLAG_STRING;

/** 评论事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_CONTENT_COMMENT;
/** 服务器下发数据Session唯一识别 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_COMMENT_SESSION_ID_STRING;
/** 内容唯一识别 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_COMMENT_CONTENT_ID_STRING;
/** 内容类型 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_COMMENT_CONTENT_TYPE_STRING;
/** 内容源 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_COMMENT_CONTENT_SOURCE_STRING;
/** 评论内容 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_COMMENT_TEXT_STRING;
/** 名称 */
FOUNDATION_EXPORT NSString *const XALEX_CONTENT_COMMENT_NAME_STRING;

/** 关注订阅事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_CHANNEL_SUBSCRIBE;
/** 服务器下发数据Session唯一识别 */
FOUNDATION_EXPORT NSString *const XALEX_CHANNEL_SUBSCRIBE_SESSION_ID_STRING;
/** 内容类型 */
FOUNDATION_EXPORT NSString *const XALEX_CHANNEL_SUBSCRIBE_CONTENT_TYPE_STRING;
/** 频道/媒体号的唯一识别，由服务端生成下发 */
FOUNDATION_EXPORT NSString *const XALEX_CHANNEL_SUBSCRIBE_CHANNEL_ID_STRING;
/** 分类的唯一识别，由服务端生成下发 */
FOUNDATION_EXPORT NSString *const XALEX_CHANNEL_SUBSCRIBE_CATEGORY_ID_STRING;
/** 标签的唯一识别，由服务器生成下发 */
FOUNDATION_EXPORT NSString *const XALEX_CHANNEL_SUBSCRIBE_TAG_ID_STRING;
/** 操作行为 */
FOUNDATION_EXPORT NSString *const XALEX_CHANNEL_SUBSCRIBE_ACTION_STRING;
/**  */
FOUNDATION_EXPORT NSString *const XALEX_CHANNEL_SUBSCRIBE_FLAG_STRING;

/** 通知栏公共事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_NOTIFICATION;
/** 通知栏的名称 */
FOUNDATION_EXPORT NSString *const XALEX_NOTIFICATION_NAME_STRING;
/** 由什么行为触发的通知栏 */
FOUNDATION_EXPORT NSString *const XALEX_NOTIFICATION_FROM_SOURCE_STRING;
/** 触发通知栏弹出结果和原因 */
FOUNDATION_EXPORT NSString *const XALEX_NOTIFICATION_RESULT_CODE_STRING;
/** 触发的通知栏场景 */
FOUNDATION_EXPORT NSString *const XALEX_NOTIFICATION_TYPE_STRING;
/** 通知样式 */
FOUNDATION_EXPORT NSString *const XALEX_NOTIFICATION_STYLE_STRING;
/** 针对弹出的通知栏各场景中所涉级到的值 */
FOUNDATION_EXPORT NSString *const XALEX_NOTIFICATION_TEXT_STRING;
/** 点击后到达的位置/页面 */
FOUNDATION_EXPORT NSString *const XALEX_NOTIFICATION_TO_DESTINATION_STRING;
/** 测试预留 */
FOUNDATION_EXPORT NSString *const XALEX_NOTIFICATION_FLAG_STRING;

/** 推送操作的公共事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_PUSH_OPERATION;
/** 推送消息ID */
FOUNDATION_EXPORT NSString *const XALEX_PUSH_OPERATION_MESSAGE_ID_STRING;
/** 动作，包括触达、展示、消失、点击。 */
FOUNDATION_EXPORT NSString *const XALEX_PUSH_OPERATION_ACTION_STRING;
/** 结果码 */
FOUNDATION_EXPORT NSString *const XALEX_PUSH_OPERATION_RESULT_CODE_STRING;
/** 推送内容类型，浏览器客户端定义 */
FOUNDATION_EXPORT NSString *const XALEX_PUSH_OPERATION_MESSAGE_TYPE_STRING;
/** 推送内容ID，来自CMS系统 */
FOUNDATION_EXPORT NSString *const XALEX_PUSH_OPERATION_CONTENT_ID_STRING;
/** 用户分群ID，来自大数据DMP系统 */
FOUNDATION_EXPORT NSString *const XALEX_PUSH_OPERATION_USER_GROUP_ID_STRING;

/** 进入首页*/
FOUNDATION_EXPORT const NSUInteger XALEX_ENTER_MAIN;
FOUNDATION_EXPORT NSString *const XALEX_ENTER_MAIN_NAME_STRING;

/** Alex公共事件-页面显示 */
FOUNDATION_EXPORT const NSUInteger XALEX_PAGE_VIEW;
/** 页面的名称 */
FOUNDATION_EXPORT NSString *const XALEX_PAGE_VIEW_NAME_STRING;
/** 页面的停留时长，通过endTimeTrack的方式来获取数据 */
/** 应用使用时长 */
FOUNDATION_EXPORT NSString *const XALEX_PAGE_VIEW_DURATION_INT;

/** Alex公共事件-APP打开 */
FOUNDATION_EXPORT const NSUInteger XALEX_APP_OPEN;
/** 打开的名称 */
FOUNDATION_EXPORT NSString *const XALEX_APP_OPEN_NAME_STRING;
/** 打开的类型，Activity或浮窗 */
FOUNDATION_EXPORT NSString *const XALEX_APP_OPEN_TYPE_STRING;

/** Alex公共事件-APP关闭 */
FOUNDATION_EXPORT const NSUInteger XALEX_APP_CLOSE;
/** 关闭的类型， Activity或浮窗 */
FOUNDATION_EXPORT NSString *const XALEX_APP_CLOSE_TYPE_STRING;
/** 关闭的种类， 正常关闭或非常关闭(强杀、异常等) */
FOUNDATION_EXPORT NSString *const XALEX_APP_CLOSE_CATEGORY_STRING;

/**
 * Alex公共事件-应用使用时长事件（时长单位为毫秒）
 */
FOUNDATION_EXPORT const NSUInteger XALEX_APP_VISIBLE_DURATION_MS;
/** 应用使用时长 */
FOUNDATION_EXPORT NSString *const XALEX_APP_VISIBLE_DURATION_MS_DURATION_INT;

/** 分段时长统计事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_SEPARATE_VISIBLE_DURATION_MS;
/** 分段名称 */
FOUNDATION_EXPORT NSString *const XALEX_SEPARATE_VISIBLE_DURATION_MS_NAME_STRING;
/** 分段时长 */
FOUNDATION_EXPORT NSString *const XALEX_SEPARATE_VISIBLE_DURATION_MS_DURATION_INT;

/** Alex公共事件-Activity存活时长事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_ACTIVITY_LIVE;
/** 存活时长 */
FOUNDATION_EXPORT NSString *const XALEX_ACTIVITY_LIVE_LIVE_TIME_INT;

/** Alex内置公共事件-亮屏时长事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_SCREEN_ON_DURATION;
/** 亮屏时长 */
FOUNDATION_EXPORT NSString *const XALEX_SCREEN_ON_DURATION_SCREEN_ON_TIME_INT;

/** Alex公共事件-亮屏 */
FOUNDATION_EXPORT const NSUInteger XALEX_SCREEN_ON;

/** Alex公共事件-灭屏 */
FOUNDATION_EXPORT const NSUInteger XALEX_SCREEN_OFF;

/** Alex内置公共事件-删除过期打点的事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_CLEAR_OVERDUE_RECORD;
/** 过期事件的数量 */
FOUNDATION_EXPORT NSString *const XALEX_CLEAR_OVERDUE_RECORD_OVERDUE_COUNT_INT;

/** Alex内置公共事件-进程启动事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_APP_START;
/** 进程名称 */
FOUNDATION_EXPORT NSString *const XALEX_APP_START_NAME_STRING;
/** 启动所有的进程的次数 */
FOUNDATION_EXPORT NSString *const XALEX_APP_START_ALL_PROCESS_COUNT_INT;
/** 启动当前进程的次数 */
FOUNDATION_EXPORT NSString *const XALEX_APP_START_CURRENT_PROCESS_COUNT_INT;

/** Alex内置公共事件-内置调试事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_INNER_DEBUG;
/** 内部调试事件的错误码 */
FOUNDATION_EXPORT NSString *const XALEX_INNER_DEBUG_ERROR_CODE_INT;
/** 内部调试事件的请求结果码 */
FOUNDATION_EXPORT NSString *const XALEX_INNER_DEBUG_RESULT_CODE_INT;

/** Alex内置公共事件-仅用于心跳，保证每天都至少有一个事件上传，不对外暴露。 */
FOUNDATION_EXPORT const NSUInteger XALEX_HEARTBEAT;

/** Alex内置公共事件-属性检查事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_ATTRIBUTE_CHECK;
/** 事件编号 */
FOUNDATION_EXPORT NSString *const XALEX_ATTRIBUTE_CHECK_EVENT_ID_STRING;
/** 属性名称 */
FOUNDATION_EXPORT NSString *const XALEX_ATTRIBUTE_CHECK_ATTR_KEY_STRING;
/** 错误信息 */
FOUNDATION_EXPORT NSString *const XALEX_ATTRIBUTE_CHECK_ERROR_INFO_STRING;
/** 检查类型 */
FOUNDATION_EXPORT NSString *const XALEX_ATTRIBUTE_CHECK_CHECK_TYPE_STRING;
/** 错误类型 */
FOUNDATION_EXPORT NSString *const XALEX_ATTRIBUTE_CHECK_ERROR_TYPE_STRING;

/** 网络监控事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_NETWORK_MONITOR;
/** 分类，标识子模块名称 */
FOUNDATION_EXPORT NSString *const XALEX_NETWORK_MONITOR_CATEGORY_STRING;
/** 请求的url */
FOUNDATION_EXPORT NSString *const XALEX_NETWORK_MONITOR_URL_STRING;
/** 请求大小，单位字节 */
FOUNDATION_EXPORT NSString *const XALEX_NETWORK_MONITOR_REQUEST_SIZE_INT;
/** 响应大小，单位字节 */
FOUNDATION_EXPORT NSString *const XALEX_NETWORK_MONITOR_RESPONSE_SIZE_INT;
/** 服务端请求标识的唯一编号 */
FOUNDATION_EXPORT NSString *const XALEX_NETWORK_MONITOR_LOG_ID_STRING;
/** 结果码，包含服务端的响应结果码与客户端的请求错误码 */
FOUNDATION_EXPORT NSString *const XALEX_NETWORK_MONITOR_RESULT_CODE_STRING;
/** 建连时长，单位为毫秒。 */
FOUNDATION_EXPORT NSString *const XALEX_NETWORK_MONITOR_CONNECT_TIME_INT;
/** 响应时长，单位为毫秒。 */
FOUNDATION_EXPORT NSString *const XALEX_NETWORK_MONITOR_RESPONSE_TIME_INT;
/** 网络监控的总时长，单位为毫秒。  */
FOUNDATION_EXPORT NSString *const XALEX_NETWORK_MONITOR_TOTAL_TIME_INT;
/** 请求等待时长，单位为毫秒。 */
FOUNDATION_EXPORT NSString *const XALEX_NETWORK_MONITOR_REQUEST_WAIT_TIME_INT;
/** 响应数据解析时长，单位为毫秒。 */
FOUNDATION_EXPORT NSString *const XALEX_NETWORK_MONITOR_PARSE_TIME_INT;
/** 发送数据组装时长，单位为毫秒。 */
FOUNDATION_EXPORT NSString *const XALEX_NETWORK_MONITOR_ASSEMBLE_TIME_INT;
/** 网络监控错误码 */
FOUNDATION_EXPORT NSString *const XALEX_NETWORK_MONITOR_ERROR_CODE_INT;
/** 错误信息描述 */
FOUNDATION_EXPORT NSString *const XALEX_NETWORK_MONITOR_ERROR_INFO_STRING;
/** 请求网络类型 */
FOUNDATION_EXPORT NSString *const XALEX_NETWORK_MONITOR_REQUEST_NETWORK_TYPE_INT;
/** DNS解析时长 */
FOUNDATION_EXPORT NSString *const XALEX_NETWORK_MONITOR_DNS_TIME_INT;
/** 网络异常信息 */
FOUNDATION_EXPORT NSString *const XALEX_NETWORK_MONITOR_EXCEPTION_INFO_STRING;

/** 数据准确性比对的公共事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_COMPARE_ACCURACY;
/** 比对的触发位置 */
FOUNDATION_EXPORT NSString *const XALEX_COMPARE_ACCURACY_TRIGGER_STRING;
/** 文件云控的版本 */
FOUNDATION_EXPORT NSString *const XALEX_COMPARE_ACCURACY_FILE_SIG_STRING;
/** 数据比对的类型 */
FOUNDATION_EXPORT NSString *const XALEX_COMPARE_ACCURACY_TYPE_STRING;
/**
 * 内置通用参数--多个事件通用，当产品线需要使用该属性时，在打点管理系统中录入该属性，并设置成允许导入神策。
 */
FOUNDATION_EXPORT NSString *const EVENT_PARAM_DURATION;

/* -- 状态打点的内置参数，不导入神策，仅用于原始日志的分析，未录入到打点管理系统中。 -- */

/** 状态打点（虚拟事件，不需要点值。） */
FOUNDATION_EXPORT const NSInteger XALEX_SETTINGS;
/** 状态打点的名称（虚拟事件） */
FOUNDATION_EXPORT NSString *const XALEX_SETTINGS_NAME;
/** 状态打点的内置参数-GMS版本 */
FOUNDATION_EXPORT NSString *const XALEX_SETTINGS_GMS_VERSION;
/** 状态打点的内置参数-GP版本 */
FOUNDATION_EXPORT NSString *const XALEX_SETTINGS_GP_VERSION;
/** 状态打点的内置参数-产品打点URL */
FOUNDATION_EXPORT NSString *const XALEX_SETTINGS_PRODUCT_URL;
/** 状态打点的内置参数-广告打点URL */
FOUNDATION_EXPORT NSString *const XALEX_SETTINGS_ADV_URL;
/** 状态打点的内置参数-体验计划是否开启 */
FOUNDATION_EXPORT NSString *const XALEX_SETTINGS_EXPERIENCE_PLAN;

/** 状态打点中记录公共库版本依赖信息的后缀的 （KEY的后缀） */
FOUNDATION_EXPORT NSString *const XALEX_SETTINGS_LIB_SUFFIX;

/* -- 内置Count事件的Key名称 --*/

/** 记录常驻进程的启动次数 */
FOUNDATION_EXPORT NSString *const COUNT_RES_PROCESS;
/** 记录亮屏的次数 */
FOUNDATION_EXPORT NSString *const COUNT_SCREEN_ON;
/** 记录灭屏的次数 */
FOUNDATION_EXPORT NSString *const COUNT_SCREEN_OFF;
/** 记录数据准确性比对的触发位置的次数 （KEY的前缀） */
FOUNDATION_EXPORT NSString *const COUNT_TRIGGER_PREFIX;

/** Firebase的事件前缀 */
FOUNDATION_EXPORT NSString *const FB_EVENT_PREFIX;

/* -- Firebase的公共事件属性（随事件可变的值） --*/
/** 事件发生时间 */
FOUNDATION_EXPORT NSString *const FB_EVENT_TIME;
/** 事件发生时的网络类型 */
FOUNDATION_EXPORT NSString *const FB_EVENT_NETWORK_TYPE;
/** 事件发生时的客户端ID */
FOUNDATION_EXPORT NSString *const FB_EVENT_CLIENT_ID;
/** 事件发生时的版本号 */
FOUNDATION_EXPORT NSString *const FB_EVENT_VERSION_CODE;

/** 标识是产品打点的接口URL */
FOUNDATION_EXPORT const NSUInteger SERVER_URL_TYPE_FOR_PRODUCT;
/** 标识是广告打点的接口URL */
FOUNDATION_EXPORT const NSUInteger SERVER_URL_TYPE_FOR_ADV;

/** 广告模块的名称 */
FOUNDATION_EXPORT NSString *const MODULE_NAME_ADV;

/**
 * 基础网络监控的模块名称
 */
FOUNDATION_EXPORT NSString *const MODULE_NAME_BASE_NETWORK_MONITOR;

/**
 * 数据准确性比对的模块名称
 */
FOUNDATION_EXPORT NSString *const MODULE_NAME_COMPARE_ACCURACY;

/**
 * 应用使用时长的标识
 */
FOUNDATION_EXPORT NSString *const APP_VISIBLE_DURATION;

/**
 * 是否是老用户（通用事件属性）
 */
FOUNDATION_EXPORT NSString *const COMMON_IS_OLD_USER;

/** 游戏自定义事件 属于特殊事件，对字段长度做放宽处理。 */
// FOUNDATION_EXPORT const NSUInteger XGAME_EVENT;
//
// FOUNDATION_EXPORT NSString *const APP_OPEN_OR_CLOSE_FLOAT_WINDOW ;
// FOUNDATION_EXPORT NSString *const APP_OPEN_OR_CLOSE_ACTIVITY;
// FOUNDATION_EXPORT NSString *const APP_CLOSE_NORMAL;
// FOUNDATION_EXPORT NSString *const APP_CLOSE_EXCEPTION ;

/**
 * 统计事件
 */
FOUNDATION_EXPORT const NSUInteger XNEPTUNE_V6_REMOTE_CONFIG;
FOUNDATION_EXPORT NSString *const XNEPTUNE_V6_REMOTE_CONFIG_ACTION_STRING;
FOUNDATION_EXPORT NSString *const XNEPTUNE_V6_REMOTE_CONFIG_SOURCE_STRING;
FOUNDATION_EXPORT NSString *const XNEPTUNE_V6_REMOTE_CONFIG_NAME_STRING;
FOUNDATION_EXPORT NSString *const XNEPTUNE_V6_REMOTE_CONFIG_COUNT_INT;
FOUNDATION_EXPORT NSString *const XNEPTUNE_V6_REMOTE_CONFIG_KEY_STRING;
FOUNDATION_EXPORT NSString *const XNEPTUNE_V6_REMOTE_CONFIG_VALUE_STRING;
FOUNDATION_EXPORT NSString *const XNEPTUNE_V6_REMOTE_CONFIG_ID_STRING;
FOUNDATION_EXPORT NSString *const XNEPTUNE_V6_REMOTE_CONFIG_DURATION_INT;
FOUNDATION_EXPORT NSString *const XNEPTUNE_V6_REMOTE_CONFIG_NUMBER_INT;
FOUNDATION_EXPORT NSString *const XNEPTUNE_V6_REMOTE_CONFIG_PUBLISH_TIME_INT;
FOUNDATION_EXPORT NSString *const XNEPTUNE_V6_REMOTE_CONFIG_RECEIVE_TIME_COST_INT;

/** 主动打开APP事件 */
FOUNDATION_EXPORT const NSUInteger XALEX_STARTUP;
/** 标识一个APP */
FOUNDATION_EXPORT NSString *const XALEX_STARTUP_APP_ID_STRING;
/** 页面的名称 */
FOUNDATION_EXPORT NSString *const XALEX_STARTUP_NAME_STRING;
/** 打开APP的来源 */
FOUNDATION_EXPORT NSString *const XALEX_STARTUP_FROM_SOURCE_STRING;
/** 页面资源ID */
FOUNDATION_EXPORT NSString *const XALEX_STARTUP_RES_ID_STRING;

// APP打开的来源：APP初始化后，进入前台页面。
FOUNDATION_EXPORT NSString *const STARTUP_FROM_SOURCE_INIT;
// APP打开的来源：应用从后台回到前台。
FOUNDATION_EXPORT NSString *const STARTUP_FROM_SOURCE_BACK;

#endif /* AlexEventsConstant_h */
