//
//  APSGameEventsConstant.h
//  AFNetworking
//
//  Created by apus on 2019/7/9.
//

#import <Foundation/Foundation.h>

/** 游戏激活事件 */
FOUNDATION_EXPORT const NSUInteger XGAME_INSTALL;
/** 应用id，唯一标识一个应用。 */
FOUNDATION_EXPORT NSString *const XGAME_INSTALL_APP_ID_STRING;
/** 账户id，唯一标识一个账户。 */
FOUNDATION_EXPORT NSString *const XGAME_INSTALL_ACCOUNT_ID_STRING;

/** 游戏打开事件 */
FOUNDATION_EXPORT const NSUInteger XGAME_STARTUP;
/** 应用id，唯一标识一个应用。 */
FOUNDATION_EXPORT NSString *const XGAME_STARTUP_APP_ID_STRING;
/** 账户id，唯一标识一个账户。 */
FOUNDATION_EXPORT NSString *const XGAME_STARTUP_ACCOUNT_ID_STRING;
/** 分辨率。 */
FOUNDATION_EXPORT NSString *const XGAME_STARTUP_RESOLUTION_STRING;
/** 服务器id。 */
FOUNDATION_EXPORT NSString *const XGAME_STARTUP_SERVER_ID_STRING;

/** 账户注册事件 */
FOUNDATION_EXPORT const NSUInteger XGAME_REGISTER;
/** 应用id，唯一标识一个应用。 */
FOUNDATION_EXPORT NSString *const XGAME_REGISTER_APP_ID_STRING;
/** 账户id，唯一标识一个账户。 */
FOUNDATION_EXPORT NSString *const XGAME_REGISTER_ACCOUNT_ID_STRING;
/** 服务器id。 */
FOUNDATION_EXPORT NSString *const XGAME_REGISTER_SERVER_ID_STRING;
/** 注册时获取到的用户年龄。 */
FOUNDATION_EXPORT NSString *const XGAME_REGISTER_AGE_INT;
/** 注册时获取到的用户性别。 */
FOUNDATION_EXPORT NSString *const XGAME_REGISTER_GENDER_STRING;
/** 账户类型，例如自有系统账户，三方系统账户，游客等。 */
FOUNDATION_EXPORT NSString *const XGAME_REGISTER_ACCOUNT_TYPE_STRING;

/** 账户登录事件 */
FOUNDATION_EXPORT const NSUInteger XGAME_LOGIN;
/** 应用id，唯一标识一个应用。 */
FOUNDATION_EXPORT NSString *const XGAME_LOGIN_APP_ID_STRING;
/** 账户id，唯一标识一个账户。 */
FOUNDATION_EXPORT NSString *const XGAME_LOGIN_ACCOUNT_ID_STRING;
/** 账户等级。 */
FOUNDATION_EXPORT NSString *const XGAME_LOGIN_ACCOUNT_LEVEL_STRING;
/** 服务器id。 */
FOUNDATION_EXPORT NSString *const XGAME_LOGIN_SERVER_ID_STRING;

/** 游戏充值事件 */
FOUNDATION_EXPORT const NSUInteger XGAME_PAYMENT;
/** 账户id，唯一标识一个账户。 */
FOUNDATION_EXPORT NSString *const XGAME_PAYMENT_ACCOUNT_ID_STRING;
/** 应用id，唯一标识一个应用。 */
FOUNDATION_EXPORT NSString *const XGAME_PAYMENT_APP_ID_STRING;
/** 服务器id。 */
FOUNDATION_EXPORT NSString *const XGAME_PAYMENT_SERVER_ID_STRING;
/** 账户等级。 */
FOUNDATION_EXPORT NSString *const XGAME_PAYMENT_ACCOUNT_LEVEL_STRING;
/** 交易的流水号。 */
FOUNDATION_EXPORT NSString *const XGAME_PAYMENT_TRANSACTION_ID_STRING;
/** 支付类型 */
FOUNDATION_EXPORT NSString *const XGAME_PAYMENT_PAYMENT_TYPE_STRING;
/** 货币类型 */
FOUNDATION_EXPORT NSString *const XGAME_PAYMENT_CURRENCY_TYPE_STRING;
/** 充值获得的游戏货币的数量。 */
FOUNDATION_EXPORT NSString *const XGAME_PAYMENT_VIRTUAL_COIN_NUM_INT;
/** 游戏内购买道具的名称。 */
FOUNDATION_EXPORT NSString *const XGAME_PAYMENT_IAP_NAME_STRING;
/** 游戏内购买道具的数量。 */
FOUNDATION_EXPORT NSString *const XGAME_PAYMENT_IAP_NUM_INT;
/** 支付的真实货币的金额。 */
FOUNDATION_EXPORT NSString *const XGAME_PAYMENT_REAL_COIN_NUM_DOUBLE;

/** 游戏交易事件 */
FOUNDATION_EXPORT const NSUInteger XGAME_ECONOMY;
/** 应用id，唯一标识一个应用。 */
FOUNDATION_EXPORT NSString *const XGAME_ECONOMY_APP_ID_STRING;
/** 账户id，唯一标识一个账户。 */
FOUNDATION_EXPORT NSString *const XGAME_ECONOMY_ACCOUNT_ID_STRING;
/** 账户等级。 */
FOUNDATION_EXPORT NSString *const XGAME_ECONOMY_ACCOUNT_LEVEL_STRING;
/** 服务器id。 */
FOUNDATION_EXPORT NSString *const XGAME_ECONOMY_SERVER_ID_STRING;
/** 游戏内虚拟物品的名称。 */
FOUNDATION_EXPORT NSString *const XGAME_ECONOMY_ITEM_NAME_STRING;
/** 交易的数量。 */
FOUNDATION_EXPORT NSString *const XGAME_ECONOMY_ITEM_NUM_INT;
/** 交易的总价。 */
FOUNDATION_EXPORT NSString *const XGAME_ECONOMY_ITEM_TOTAL_PRICE_DOUBLE;
/** 交易类型 */
FOUNDATION_EXPORT NSString *const XGAME_ECONOMY_DEAL_TYPE_STRING;

/** 游戏任务事件 */
FOUNDATION_EXPORT const NSUInteger XGAME_QUEST;
/** 账户id，唯一标识一个账户。 */
FOUNDATION_EXPORT NSString *const XGAME_QUEST_ACCOUNT_ID_STRING;
/** 应用id，唯一标识一个应用。 */
FOUNDATION_EXPORT NSString *const XGAME_QUEST_APP_ID_STRING;
/** 账户等级。 */
FOUNDATION_EXPORT NSString *const XGAME_QUEST_ACCOUNT_LEVEL_STRING;
/** 服务器id。 */
FOUNDATION_EXPORT NSString *const XGAME_QUEST_SERVER_ID_STRING;
/** 任务/关卡/副本的编号或名称。 */
FOUNDATION_EXPORT NSString *const XGAME_QUEST_QUEST_ID_STRING;
/** 当前的任务/关卡/副本的状态 */
FOUNDATION_EXPORT NSString *const XGAME_QUEST_QUEST_STATUS_STRING;
/** 当前的任务/关卡/副本的类型。 */
FOUNDATION_EXPORT NSString *const XGAME_QUEST_QUEST_TYPE_STRING;
/** 关卡数 */
FOUNDATION_EXPORT NSString *const XGAME_QUEST_QUEST_INDEX_INT;
/** 游戏任务名称 */
FOUNDATION_EXPORT NSString *const XGAME_QUEST_QUEST_NAME_STRING;
/** 关卡内的进度 */
FOUNDATION_EXPORT NSString *const XGAME_QUEST_PROGRESS_INT;
/** 次数 */
FOUNDATION_EXPORT NSString *const XGAME_QUEST_TIMES_INT;

/** 游戏广告操作事件 */
FOUNDATION_EXPORT const NSUInteger XGAME_ADV_OPERATION;
/** 广告的触发场景 */
FOUNDATION_EXPORT NSString *const XGAME_ADV_OPERATION_TRIGGER_STRING;
/** 状态 */
FOUNDATION_EXPORT NSString *const XGAME_ADV_OPERATION_STATUS_STRING;
/** 是否有缓存 */
FOUNDATION_EXPORT NSString *const XGAME_ADV_OPERATION_IS_READY_INT;
/** 广告类型。 */
FOUNDATION_EXPORT NSString *const XGAME_ADV_OPERATION_AD_TYPE_STRING;
/** 账户id，唯一标识一个账户。 */
FOUNDATION_EXPORT NSString *const XGAME_ADV_OPERATION_ACCOUNT_ID_STRING;
/** 应用id，唯一标识一个应用。 */
FOUNDATION_EXPORT NSString *const XGAME_ADV_OPERATION_APP_ID_STRING;
/** 服务器id。 */
FOUNDATION_EXPORT NSString *const XGAME_ADV_OPERATION_SERVER_ID_STRING;

/** 游戏自定义事件 */
FOUNDATION_EXPORT const NSUInteger XGAME_EVENT;
/** 应用id，唯一标识一个应用。 */
FOUNDATION_EXPORT NSString *const XGAME_EVENT_APP_ID_STRING;
/** 账户id，唯一标识一个账户。 */
FOUNDATION_EXPORT NSString *const XGAME_EVENT_ACCOUNT_ID_STRING;
/** 服务器id。 */
FOUNDATION_EXPORT NSString *const XGAME_EVENT_SERVER_ID_STRING;
/** 自定义事件的名称。 */
FOUNDATION_EXPORT NSString *const XGAME_EVENT_NAME_STRING;
/** 自定义的参数Key和Value，传Json字符串。 */
FOUNDATION_EXPORT NSString *const XGAME_EVENT_CUSTOM_PARAMS_STRING;

/** GDPR公共事件 */
FOUNDATION_EXPORT const NSUInteger XGAME_GDPR;
/** 隐私弹窗页的动作 */
FOUNDATION_EXPORT NSString *const XGAME_GDPR_ACTION_STRING;
/** 游戏核心点击事件，由用户操作触发。 */
FOUNDATION_EXPORT const NSUInteger XGAME_CORE_CLICK;
/** 控件的名称 */
FOUNDATION_EXPORT NSString *const XGAME_CORE_CLICK_NAME_STRING;
/** 游戏核心操作事件，一般不是由用户操作触发。 */
FOUNDATION_EXPORT const NSUInteger XGAME_CORE_OPERATION;
/** 操作名称 */
FOUNDATION_EXPORT NSString *const XGAME_CORE_OPERATION_NAME_STRING;
/** 操作状态 */
FOUNDATION_EXPORT NSString *const XGAME_CORE_OPERATION_STATUS_STRING;
/** 游戏核心展示事件，核心页面或组件展示时触发。 */
FOUNDATION_EXPORT const NSUInteger XGAME_CORE_SHOW;
/** 页面或控件名称 */
FOUNDATION_EXPORT NSString *const XGAME_CORE_SHOW_NAME_STRING;
